#!/bin/ksh 

echo `date` $0 `date -u` begin

set -xa
export PS4='$SECONDS + '
date

export total_tasks=${total_tasks:-6}
export gefsmpexec=${gefsmpexec:-"mpirun -n $total_tasks"}
export APRUN=${gefsmpexec_mpmd:-"mpirun -n $total_tasks cfp mpmd_cmdfile"}

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/${job}.${pid}}

mkdir -p $DATA
cd $DATA

######################################
# Set up the cycle variable
######################################
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gens}
export RUN=${RUN:-gefs}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# SENDECF  - Flag Events on ECF
# VERBOSE  - Specify Verbose Output
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export VERBOSE=${VERBOSE:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}

export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
export USHgefs=${USHgefs:-$HOMEgefs/ush}
export FIXgefs=${FIXgefs:-$HOMEgefs/fix/fix_gefs}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

export REDOUT='1>>'
export REDERR='2>'

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

##############################################
echo set parameters using gefs.parm
##############################################
. $PARMgefs/gefs.parm
. $PARMgefs/gefs_ensstat.parm

##############################################
# Define COM directories
##############################################
export COMIN=$COMROOT/${NET}/${envir}/${RUN}.${PDY}/$cyc/atmos
export COMOUT=$COMROOT/${NET}/${envir}/${RUN}.${PDY}/$cyc/atmos

mkdir -m 775 -p $COMOUT/pgrbsubx1p0
mkdir -m 775 -p $COMOUT/subx_daily
mkdir -m 775 -p $COMOUT/subx_daily/output_p1
mkdir -m 775 -p $COMOUT/subx_daily/output_p2
mkdir -m 775 -p $COMOUT/subx_daily/output_p3

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

##############################################
# Clean COM directories
##############################################
rm -f $COMOUT/pgrbsubx1p0/*
rm -f $COMOUT/subx_daily/output_p1/*
rm -f $COMOUT/subx_daily/output_p2/*
rm -f $COMOUT/subx_daily/output_p3/*

##############################################
# Execute ecflow scripts
##############################################
rm -f subxprdgen.cmdfile
for mem in $MEMLIST;do

	subdata=${DATA}/$mem
	if [ ! -d ${subdata} ]; then
		mkdir -p ${subdata};
	fi
	outfile=${subdata}/${mem}.out

	echo "$HOMEgefs/scripts/exgefs_subxprdgen.sh.ecf ge${mem} 2>&1 >${outfile}" >> subxprdgen.cmdfile
done

cat subxprdgen.cmdfile
chmod 775 subxprdgen.cmdfile
export MP_CMDFILE=${DATA}/subxprdgen.cmdfile
export SCR_CMDFILE=$MP_CMDFILE  # Used by mpiserial on Theia
export MP_PGMMODEL=mpmd
rm -f mpmd_cmdfile
ln -s $MP_CMDFILE mpmd_cmdfile

$APRUN 

rc=$?
if [[ $rc -ne 0 ]]; then
	msg="FATAL ERROR: $0 failed!"
	echo "`date`    $msg"
	postmsg "$jlogfile" "$msg"
	export err=1
	err_chk
	exit $err
fi

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
